# Generated by Django 4.1.6 on 2023-02-05 06:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                ("link", models.CharField(max_length=1000)),
                ("new", models.CharField(max_length=6)),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.UUID("ceb0bf4a-3c9a-41c6-91cb-edccd4b35070"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
    ]
